# This is a basic workflow to help you get started with Actions

name: build jellyfin-with-fonts

# Controls when the workflow will run
on:
  push:
    branches:
    - main
  schedule:
    - cron:  '0 0 * * *' # run crontab every day 00:00

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: run build.sh
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          echo "start build docker image"
          bash build.sh
          echo "finished"

